CREATE TABLE TESTUSERS (
	   ID INT NOT NULL AUTO_INCREMENT
     , NAME VARCHAR(30) NOT NULL
     , SURNAME VARCHAR(30) NOT NULL
     , BIRTHDATE DATE
     , UNIQUE UQ_USERS_1 (ID)
     , PRIMARY KEY (ID)
);

CREATE TABLE FRIENDSHIPS (
       USERID1 INT NOT NULL
     , USERID2 INT NOT NULL
     , TIMESTAMP DATE
     , CONSTRAINT FK_USERID1 FOREIGN KEY (USERID1) REFERENCES TESTUSERS (ID)
	 , CONSTRAINT FK_USERID2 FOREIGN KEY (USERID2) REFERENCES TESTUSERS (ID)
	 , CONSTRAINT UQ_FRIENDSHIPS UNIQUE (USERID1, USERID2)
);

CREATE TABLE POSTS (
       ID INT NOT NULL AUTO_INCREMENT
     , USERID INT NOT NULL
     , TEXT VARCHAR(500) NOT NULL
     , TIMESTAMP DATE
     , PRIMARY KEY (ID)
     , CONSTRAINT FK_POSTS FOREIGN KEY (USERID) REFERENCES TESTUSERS (ID)
);

CREATE TABLE LIKES (
       POSTID INT NOT NULL
     , USERID INT NOT NULL
     , TIMESTAMP DATE
     , CONSTRAINT FK_POSTID FOREIGN KEY (POSTID) REFERENCES POSTS (ID)
	 , CONSTRAINT FK_USERID FOREIGN KEY (USERID) REFERENCES TESTUSERS (ID)
	 , CONSTRAINT UQ_LIKES UNIQUE (POSTID, USERID)
);